[workspace]
members = [
    "rust-pratice/basic",
    "tour-of-rust",
    "programming-rust",
    "rust-in-action",
 #   "example-crypto-hash-function-useage",
    "cs251-cbt",
    "build-blockchain-in-rust",
]
