[workspace]
members = [
    "rust-pratice/basic",
    "tour-of-rust",
    "programming-rust",
    "rust-in-action",
    "cs251-cbt",
    "build-blockchain-in-rust",
    "rust-for-rustaceans/rust-for-rustaceans",
    "rust-algorithms",
]
