[workspace]
members = [
    "course-1",
    "course-30",
    "rust-pratice/basic",
    "algorithms-rs",
    "workspace",
    "tour-of-rust",
    "monkey-interpter",
    "futures-explained-in-200-lines-of-rust",
]
