[package]
name = "cs251-cbt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
base64 = "0.21.0"
serde = "1.0.152"
serde_derive = "1.0.152"
serde_json = "1.0.91"
sha2 = "0.10.6"
